### ISSUE TITLE
什么时候能出支持lua5.1/luajit的版本？

### ISSUE THREAD

**Issue by qingfenghuang** [DavidFeng/lua-flatbuffers#1]
如题，谢谢！

**Comment by DavidFeng** [comment]
由于本项目其实并没有用到5.3专有特性，所以其实只要修改下C模块，就可以在其他版本的Lua中使用了。

如果有需要，我抽时间完善一下吧。

另外，也欢迎发送pull request

**Comment by qingfenghuang** [comment]
好的 谢谢~

**Comment by DavidFeng** [comment]
目前暂时没有计划支持低版本,所以先关掉这个issue了
