### ISSUE TITLE
请问怎么编译，我一直编译不通过

### ISSUE THREAD

**Issue by kennylixi** [DavidFeng/lua-flatbuffers#7]
lua版本5.3.5
以下是编译错误信息（window系统）：
C:\local\lua-flatbuffers-master>make
process_begin: CreateProcess(NULL, uname -s, ...) failed.
make: Makefile:6: pipe: No error
cc -shared -o buffer.so -std=c99 -O2 -fPIC -Wall buflib.c
process_begin: CreateProcess(NULL, cc -shared -o buffer.so -std=c99 -O2 -fPIC -Wall buflib.c, ...) failed.
make (e=2): 系统找不到指定的文件。
make: *** [Makefile:23: buffer.so] Error 2

**Comment by DavidFeng** [comment]
Windows系统，需要设置好编译环境。

搜cygwin有更多信息。

你也可以用visual studio创建dll工程，一步步加源码，编译。


2018年10月3日(水) 0:04 kennylixi <notifications@github.com>:
